Multiple updates - separated by commit message
USGS-Astrogeology/autocnet pull request #527
Opened 2021-02-11 02:55 UTC by jlaura

These are the changes that have been made during CTX work.

2021-02-11 05:19 UTC, AustinSanders requested changes

2021-02-11 05:19 UTC, AustinSanders commented on autocnet/graph/network.py
> +            self.redis_queue.delete(q)
The docs suggest that we're deleting messages from the queues, but .delete() removes the queue entirely.  Should we use [.empty()](https://github.com/rq/rq/blob/016da14723d21f6801b19cbff97f2fb9bee5c5db/rq/queue.py#L115) or can we clarify in the docs that the queues will be deleted?

2021-02-11 05:19 UTC, AustinSanders commented on autocnet/cg/cg.py
> +              If True (default) compute the minimum rotated rectable bounding
Should this be "minimum rotated rectangle"?

2021-02-11 13:52 UTC, jlaura commented on autocnet/cg/cg.py
> +              If True (default) compute the minimum rotated rectable bounding
yes

2021-02-11 13:57 UTC, jlaura commented
@AustinSanders Updated for all comments. Thanks for the review!

2021-02-12 05:52 UTC, AustinSanders approved these changes

2021-02-12 15:15 UTC, Kelvinrr approved these changes
seems fine to me

2021-02-13 15:00 UTC, ladoramkershner commented on autocnet/matcher/subpixel.py
> -
This either needs to be kept in the code, or subpixel_register_point needs to work with the object handed in. Right now subpixel_register_point just fails when trying to preform the query on line 1459.

I tried using the query_string argument to get around this (SELECT id FROM points) but the query return is still considered a point object when it gets down to line1459

2021-02-19 15:36 UTC, merged

2021-02-19 19:59 UTC, ladoramkershner commented
@jlaura @Kelvinrr 
This still does not have the fix in it I was asking for..should we revert or open a new PR?