MI Matcher Addition
USGS-Astrogeology/autocnet pull request #559
Opened 2021-05-20 21:00 UTC by acpaquette

Adds the mutual information matcher for use within autocnet. Mainly through the `subpixel_template` method where the mutual_information function should be passed in as the `func=mutual_information` argument.

2021-05-20 21:34 UTC, jessemapel reviewed
It looks like we can merge this as-is right now and in the future we can test swapping in the scikit image MI matcher function. This looks good to me, but I'm really bad at reviewing autocnet so I'm going to let some other's chime in too.

2021-05-20 21:37 UTC, jessemapel commented on autocnet/matcher/tests/test_mutual_information.py
> +    assert max_corr == 2.9755967600033015
I would add a simple sanity check on the correlation map. Maybe just check the dimensions and that the min/max are within the expected range, I think between 0 and the number of bins.

2021-05-21 20:24 UTC, jlaura requested changes

2021-05-21 20:24 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +def mi(t1, t2, **kwargs):
Can we name this something more descriptive? Or use it as a context inside of mutual_information?

2021-05-21 20:24 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +
Need a see also for what the kwargs coming in are. Right now, I wouldn't know where to even look if I used just the doc string.

2021-05-21 20:24 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +def mi(t1, t2, **kwargs):
Also - did my gist include a 'from' line that attributed this code to the blog post that I initial found it on?

2021-05-21 20:24 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +
Where is the 2x the size defined? Looks like I could run this with identically sized d_template, s_image ndarrays and it would work fine.

2021-05-21 20:24 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +    y_offset = max_i - (template_size[0]/2)
This is not sub pixel enabled right now. Is that intentional? Subpixel weighting should be very easy to copy/paste in (cleaner would be to refactor to get the subpixel weighting into a function that both this and the linked call).

Lines 49-72 show how to get a subpixel weighting using the corrmap: https://github.com/USGS-Astrogeology/autocnet/blob/dev/autocnet/matcher/naive_template.py#L49

2021-05-21 21:59 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +def mi(t1, t2, **kwargs):
There is no `from` line but there is a link to scikit image if that is where you obtained the implementation. Then scikit image also has a link to [this paper](https://www.sciencedirect.com/science/article/abs/pii/S0031320398000910?via%3Dihub) that outlines their implementation

2021-05-21 21:59 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +
This kinda depends if we use scikit images implementation or the matcher that was in your gist

2021-05-21 22:03 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +
It can in its current state. There are a few options:
- Force user to provide the expected dimensions
- Only ask for an image or template size then calculate the other
- Ignore the dimension constraint but don't search a subset of the search space
- Buffer the search space so that the template can still exhaust the whole search space (scikit image approach)

2021-05-21 22:06 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +    y_offset = max_i - (template_size[0]/2)
This was copied from the notebook and I wasn't sure if we wanted to shoot for subpixel registration for the image registration sprint. This is something I can add to the PR

2021-05-24 11:45 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +
All of those options suggest to me that the docs string is wrong and needs to be updated to be correct. Does this code have a size requirement?

2021-05-24 19:25 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +
Yes, that's correct. The only real size requirement is that the template must be smaller than the search image size

2021-05-24 19:28 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +
Is that something that should be addressed in the `subpixel_template_classic` or in this function?

2021-05-24 21:20 UTC, jessemapel commented on autocnet/matcher/mutual_information.py
> +def mi(t1, t2, **kwargs):
Making this a contextual function means we can't unit test it anymore. I would move this back out to a module function and rename these. This function should be mutual_information as it computes the mutual information between two images. The other function should be called mutual_information_match as it matches two images using the mutual information.

2021-05-24 21:36 UTC, jessemapel commented on autocnet/matcher/tests/test_mutual_information.py
> +    assert np.average(corr_map) == 1.3199548152066989
Average is a really bad sanity check as it's going to be highly sensitive and doesn't actually tell us anything. I did a little bit more research and it turns out bounds on MI are rather complex, so here we should just sanity check the lower bound of 0.

2021-05-31 14:03 UTC, jlaura commented on autocnet/matcher/mutual_information.py
> +
> Where the search area is 2x the size of the template image

Needs to be changed. from your comment:

> Yes, that's correct. The only real size requirement is that the template must be smaller than the search image size

The doc string is wrong.

2021-05-31 14:04 UTC, jlaura reviewed
This has 2 outstanding comments and then likely needs a rebase. After that, I think this is good togo.

2021-08-13 12:10 UTC, jlaura commented
@acpaquette Here is the improved center of gravity based subpixel approach: https://github.com/USGS-Astrogeology/autocnet/blob/dev/autocnet/matcher/naive_template.py#L62; using an implementation right from scipy and then the same logic to back out the transformation chain as the naive template matcher.

2021-08-17 20:51 UTC, acpaquette commented on autocnet/matcher/tests/test_mutual_information.py
> +    assert np.average(corr_map) == 1.3199548152066989
Fixed with a lower bound test!

2021-08-17 20:52 UTC, acpaquette commented on autocnet/matcher/mutual_information.py
> +def mi(t1, t2, **kwargs):
Moved the contextual mutual_information function out of the matcher

2021-08-17 21:06 UTC, jlaura approved these changes

2021-08-17 21:11 UTC, jessemapel approved these changes

2021-08-19 12:49 UTC, jlaura commented
@acpaquette Looks like the MI test needs a `pytest.approx` to some reasonable number of decimal places. One other minor request - would you mind updating the changelog to add this PR?

I'll open an issue that the overlay test is leaving a dangling session and we can fix that in another PR.

2021-08-20 21:57 UTC, merged