Phase Roi Update
USGS-Astrogeology/autocnet pull request #629
Opened 2021-12-17 18:04 UTC by acpaquette

Updates the iterative_phase function and subpixel_phase functions to use Roi objects rather than numpy arrays.

These updated functions are now also going to return affine transformations rather than updated coordinates. The affine matrices for both iterative_phase and subpixel_phase are walking_image to reference image.

2021-12-19 13:38 UTC, jlaura requested changes

2021-12-19 13:38 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    walking_template = walking_roi.clip(affine)
It does not look like the ROI object was updated to take an affine in the subpixelapi branch. Did I miss the change? I also don't see the change in the PR.

2021-12-19 13:38 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    walking_roi : Object
@gsn9 @Kelvinrr walking_roi vs moving_roi - can you all pick one and stick with it? It will make things more readable and let me write an architecture document about the sub pixel API more easily.

2021-12-19 13:38 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    new_affine = AffineTransform(translation=(shift_x, shift_y))
The template PR that was merged, I believe was applying -shift_x, -shift_y. This is shift_x, shift_y. Shouldn't these be consistent? Seem that the caller would need to apply direct vs inverse transformation if these are swapped.

@Kelvinrr

2021-12-19 13:38 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    return new_affine, (error, diffphase)
Similar comment. On the template PR, the return was a straight list, so unpacking is different than here. Shouldn't these be standardized?

2021-12-22 05:25 UTC, acpaquette commented on autocnet/matcher/subpixel.py
> +    walking_template = walking_roi.clip(affine)
@jlaura I made this change but likely reverted it in the Roi clip function. I have been working on adding it back in but I am running into issues between the GeoDataset object and just a numpy array as the data. We basically lose all notion of a x, any y coordinate after cropping clipping the data. So applying the affine to get a subwindow of the Roi no longer operates on a GeoDataset object but a numpy array. 

This is difficult as our idea of an individual x, y coord that is agnostic of the window we are extracting is no longer present. If your x, y coord is (250, 250) and you extract a (200, 200) window over a numpy array, (250, 250) no longer work as array indices. It would be nice to maintain the idea of a center coordinate that is truly agnostic of the array size, which is what I have been fighting with in the Roi object

2021-12-22 05:25 UTC, acpaquette commented on autocnet/matcher/subpixel.py
> +    walking_roi : Object
I figured we could do a pass once all of these work is finished and tidied up. I agree we should pick one. We never really decided which

2021-12-22 05:28 UTC, acpaquette commented on autocnet/matcher/subpixel.py
> +    new_affine = AffineTransform(translation=(shift_x, shift_y))
We are trying to keep them consistent but the different subpixel matchers produce different x, y shifts. Some produce shifts from reference -> walking while others, like the Phase matcher produce x, y shifts from walking -> reference. I think it is reasonable to expect all of our subpixel matchers to produce one of the above forms but that means certain matchers will return `AffineTransform(translation=(shift_x, shift_y))` or AffineTransform(translation=(-shift_x, -shift_y))

2021-12-22 05:29 UTC, acpaquette commented on autocnet/matcher/subpixel.py
> +    return new_affine, (error, diffphase)
Chain these algorithms together is something that we discussed but I don't know if we got to this in practice. I think a straight list is fine for now

2021-12-23 13:56 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    return new_affine, (error, diffphase)
cool - this is something else that we can standardize post merge on all of these.

2021-12-23 13:58 UTC, jlaura commented on autocnet/matcher/subpixel.py
> +    walking_template = walking_roi.clip(affine)
Gotcha, without playing around in a notebook with this, I suspect any 'ideas' I have would be half baked and less than helpful. I'll leave this PR open until this change is pushed in though because I think without it, this code will not function. Is that a correct assumption?

2021-12-24 03:47 UTC, acpaquette commented on autocnet/matcher/subpixel.py
> +    walking_template = walking_roi.clip(affine)
I think that we can handle this differently in the algorithms to avoid this problem. Unfortunately it makes the algorithms messy. Rather than updating the affine per run of iterative affine, we can update the position of the x, y coordinate in the Roi and add that to the final affine. This prevents the iterative clipping, avoiding this problem mentioned previously. However, it does require that we maintain the state of the passed in Roi objects which is messy, since the algorithm updates the internal state of the Roi object

2021-12-24 03:50 UTC, acpaquette commented on autocnet/transformation/roi.py
> +            #                      "a smaller region of interest" )
This can likely go since we are wrapping with mode set to reflect

2022-01-02 13:34 UTC, merged